os:
    - linux
before_install: 
    - sudo apt-add-repository ppa:ubuntu-sdk-team/ppa
    - sudo apt-get update
install: sudo apt-get install qtdeclarative5-dev
script: echo "success"
after_success: echo "after success"
