os:
    - linux
before_install:
    - sudo apt-get --yes update
install:
    - sudo apt-get install p7zip
    - scripts/install-qt Qt5.3.0
    - find Qt5.3.0 -print
script:
    - env
    - $TRAVIS_BUILD_DIR/Qt5.3.0/bin/qmake -version
    - echo "success"
after_success: echo "after success"
