os:
    - linux
before_install:
    - sudo apt-add-repository --yes ppa:ubuntu-sdk-team/ppa
    - sudo apt-get --yes update
install:
    - sudo apt-get install p7zip
    - scripts/install-qt Qt5.3.0
    - find Qt5.3.0 -print
script: echo "success"
after_success: echo "after success"
