os:
    - linux
before_install:
    - sudo apt-get --yes update
install:
    - sudo apt-get install p7zip
    - scripts/install-qt Qt
    - find Qt -print
    - export PATH=$TRAVIS_BUILD_DIR/Qt/5.3/gcc_64/bin:$PATH
script:
    - env
    - $TRAVIS_BUILD_DIR/Qt/5.3/gcc_64/bin/qmake -version
    - echo "success"
after_success: echo "after success"
